title: liangfei.me 
author:
  name: Lyndon Liang
  email: njliangfei@gmail.com
description: >-
  A History-loving, Code-writing Entreprenuer Fluent in Chinse, Japanse and English
baseurl: ""
url: "https://liangfei.me"

# Analytics
google_analytics: G-WGQHJGVC9B

# Build settings
remote_theme: jekyll/minima@master
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji


minima:
  social_links:
    - { title: github, icon: github, url: "https://github.com/liangfeidotme" }
    - { title: twitter, icon: twitter, url: "https://twitter.com/liangfeidotme" }
    - { title: facebook, icon: facebook, url: "https://www.facebook.com/liangfei.me" }
    - { title: instagram, icon: instagram, url: "https://www.instagram.com/liangfei.me" }
    - { title: linkedin, icon: linkedin, url: "https://www.linkedin.com/in/lyndon-liang-895707229/" }

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
