title: liangfei.me 
email: njliangfei@gmail.com
description: >-
  Living in Hangzhou, 
  running a small business,
  like reading.
baseurl: ""
url: "https://liangfei.me"

# Analytics
google_analytics: G-WGQHJGVC9B

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Social
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/liangfeidotme" }
    - { platform: twitter,  user_url: "https://twitter.com/liangfeidotme" }
    - { platform: facebook,  user_url: "https://www.facebook.com/liangfei.me" }
    - { platform: instagram,  user_url: "https://www.instagram.com/liangfei.me" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/lyndon-liang-895707229/" }

header_pages:
  - biz.md
  - learning.md
  - reading.md
  - about.html
  - hz.md

# Comments
disqus:
  shortname: liangfei-me

collections: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
