title: Lyndon
email: njliangfei@gmail.com
description: >-
  Living in Hangzhou, 
  running a small business,
  like reading.
baseurl: ""
url: "https://liangfei.me"
twitter_username: liangfeidotme
github_username:  liangfeidotme

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - hz.md
  - biz.md
  - reading.md
  - about.html

collections:
  hz-gates:
    output: true
    sort_by: order

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
